# Generated by Django 3.1.1 on 2020-10-20 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('3', '3D'), ('EC', 'E-commerce'), ('AG', 'Agency'), ('AP', 'App'), ('BC', 'Blockchain'), ('BG', 'Blog'), ('BK', 'Book'), ('BS', 'Business'), ('CS', 'Coming Soon'), ('CM', 'Community'), ('CO', 'Corporate'), ('CR', 'Creative'), ('CC', 'Cryptocurrency'), ('CL', 'Culture'), ('DS', 'Design Tools'), ('DV', 'Development Tools'), ('ED', 'Education'), ('EN', 'Entertainment'), ('EV', 'Event'), ('FS', 'Fashion'), ('FN', 'Finance'), ('FD', 'Food & Drinks'), ('FI', 'Furniture & Interiors'), ('GR', 'Gradient'), ('HF', 'Health & Fitness'), ('HT', 'Hosting'), ('IL', 'Illustration'), ('IN', 'Insurance'), ('IS', 'Isometric'), ('MG', 'Magazine'), ('MN', 'Minimal'), ('MS', 'Miscellaneous'), ('OT', 'Outdoors & Travel'), ('PN', 'Pattern'), ('PG', 'Photography'), ('PF', 'Portfolio'), ('PM', 'Product Management'), ('PD', 'Productivity'), ('PT', 'Prototype'), ('RE', 'Real Estate'), ('SW', 'Software'), ('SD', 'Studio'), ('TC', 'Technology'), ('TG', 'Typography')], max_length=2)),
                ('color', models.CharField(choices=[('AQ', 'Aqua'), ('BK', 'Black'), ('BL', 'Blue'), ('BR', 'Brown'), ('GR', 'Gray'), ('GN', 'Green'), ('LM', 'LIME'), ('MR', 'Maroon'), ('ML', 'Multiple Colors'), ('NV', 'Navy'), ('OL', 'Olive'), ('OR', 'Orange'), ('PN', 'Pink'), ('PR', 'Purple'), ('RD', 'Red'), ('TL', 'Teal'), ('UV', 'Ultra Violet'), ('WT', 'White'), ('YL', 'Yellow')], max_length=2)),
                ('image_url', models.CharField(max_length=2000)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.website')),
            ],
        ),
    ]
